"""Auditor bundle generator — single ZIP with everything an auditor needs.

Assembles compliance posture, AI system register, FRIAs, serious incident
reports, policies, custom rules, and audit log into a structured ZIP.
"""

from __future__ import annotations

import io
import json
import uuid
import zipfile
from datetime import UTC, date, datetime, timedelta
from typing import Any

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.compliance.fria_html_template import render_fria_html
from app.compliance.incident_report_template import render_incident_html
from app.db.models import (
    AISystem,
    AISystemSupplier,
    AuditLog,
    FRIADocument,
    Org,
    Policy,
    SeriousIncident,
)
from app.services.compliance_posture_service import compute_posture, overall_status

log = structlog.get_logger()


async def generate_bundle(
    db: AsyncSession,
    org_id: uuid.UUID,
    period_start: date | None = None,
    period_end: date | None = None,
) -> bytes:
    """Generate a complete auditor bundle as ZIP bytes."""
    if period_end is None:
        period_end = date.today()
    if period_start is None:
        period_start = period_end - timedelta(days=180)

    # Load org
    org_result = await db.execute(select(Org).where(Org.id == org_id))
    org = org_result.scalar_one()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # README
        zf.writestr("README.md", _readme(org, period_start, period_end))

        # Metadata
        metadata = await _build_metadata(db, org, period_start, period_end)
        zf.writestr("metadata.json", json.dumps(metadata, indent=2, default=str))

        # Compliance posture
        posture = await compute_posture(db, org_id)
        posture_data = [
            {
                "id": o.id,
                "article": o.article,
                "title": o.title,
                "status": o.status,
                "evidence": o.evidence,
                "remediation": o.remediation,
            }
            for o in posture
        ]
        zf.writestr(
            "compliance-posture.json",
            json.dumps(posture_data, indent=2, default=str),
        )

        # AI Systems register
        await _add_systems(zf, db, org_id)

        # FRIAs
        await _add_frias(zf, db, org_id)

        # Serious incidents
        await _add_serious_incidents(zf, db, org_id)

        # Policies + custom rules
        await _add_policies(zf, db, org_id)

        # Audit log
        await _add_audit_log(zf, db, org_id, period_start, period_end)

    return buf.getvalue()


def _readme(org: Org, start: date, end: date) -> str:
    return f"""# Parry Auditor Bundle

**Organization:** {org.name}
**Covered period:** {start} to {end}
**Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}

## Contents

- `metadata.json` — Bundle metadata and obligation checklist
- `compliance-posture.json` — Current compliance posture snapshot
- `systems-register/` — AI system register with supplier info
- `fria/` — Approved FRIA documents
- `incidents/` — Serious incident reports
- `policies/` — Active policies and custom detection rules
- `audit-log/` — Audit log export for the covered period

## Verification

The audit log includes hash-chained entries. See
`audit-log/chain-verification.md` for offline verification instructions.

## Disclaimer

This bundle was generated by Parry to assist with EU AI Act Article 26
compliance documentation. It is not legal advice. The deployer remains
responsible for compliance.
"""


async def _build_metadata(
    db: AsyncSession, org: Org, start: date, end: date
) -> dict[str, Any]:
    posture = await compute_posture(db, org.id)
    fria_count = await db.execute(
        select(FRIADocument)
        .where(FRIADocument.org_id == org.id, FRIADocument.status == "approved")
    )
    frias = list(fria_count.scalars().all())

    incident_count = await db.execute(
        select(SeriousIncident).where(SeriousIncident.org_id == org.id)
    )
    incidents = list(incident_count.scalars().all())

    return {
        "schema_version": "1.0",
        "org_id": str(org.id),
        "org_name": org.name,
        "generated_at": datetime.now(UTC).isoformat(),
        "covered_period": {"start": str(start), "end": str(end)},
        "obligations_checklist": {o.id: o.status for o in posture},
        "overall_status": overall_status(posture),
        "fria_count": len(frias),
        "serious_incident_count": len(incidents),
    }


async def _add_systems(
    zf: zipfile.ZipFile, db: AsyncSession, org_id: uuid.UUID
) -> None:
    result = await db.execute(
        select(AISystem).where(AISystem.org_id == org_id)
    )
    systems = list(result.scalars().all())

    systems_data = []
    for s in systems:
        # Load suppliers
        sup_result = await db.execute(
            select(AISystemSupplier).where(AISystemSupplier.system_id == s.id)
        )
        suppliers = [
            {
                "supplier_name": sp.supplier_name,
                "model_id": sp.model_id,
                "first_used_at": sp.first_used_at.isoformat(),
                "last_used_at": sp.last_used_at.isoformat(),
                "event_count": sp.event_count,
                "jurisdiction": sp.jurisdiction,
            }
            for sp in sup_result.scalars().all()
        ]
        systems_data.append({
            "id": str(s.id),
            "name": s.name,
            "description": s.description,
            "risk_level": s.risk_level,
            "intended_purpose": s.intended_purpose,
            "deployer_name": s.deployer_name,
            "provider_name": s.provider_name,
            "deployment_date": str(s.deployment_date) if s.deployment_date else None,
            "fria_status": s.fria_status,
            "annex_iii_category": s.annex_iii_category,
            "jurisdiction": s.jurisdiction,
            "suppliers": suppliers,
        })

    zf.writestr(
        "systems-register/ai-systems.json",
        json.dumps(systems_data, indent=2, default=str),
    )


async def _add_frias(
    zf: zipfile.ZipFile, db: AsyncSession, org_id: uuid.UUID
) -> None:
    result = await db.execute(
        select(FRIADocument).where(
            FRIADocument.org_id == org_id,
            FRIADocument.status == "approved",
        )
    )
    for doc in result.scalars().all():
        # JSON content
        zf.writestr(
            f"fria/{doc.system_id}-v{doc.version}.json",
            json.dumps(doc.content, indent=2, default=str),
        )
        # HTML version
        try:
            html = render_fria_html(doc)
            zf.writestr(f"fria/{doc.system_id}-v{doc.version}.html", html)
        except Exception:
            log.warning("bundle.fria_html_failed", fria_id=str(doc.id), exc_info=True)


async def _add_serious_incidents(
    zf: zipfile.ZipFile, db: AsyncSession, org_id: uuid.UUID
) -> None:
    result = await db.execute(
        select(SeriousIncident).where(SeriousIncident.org_id == org_id)
    )
    incidents = list(result.scalars().all())

    for si in incidents:
        zf.writestr(
            f"incidents/serious-{si.id}.json",
            json.dumps(si.report_content, indent=2, default=str),
        )
        try:
            html = render_incident_html(si)
            zf.writestr(f"incidents/serious-{si.id}.html", html)
        except Exception:
            log.warning("bundle.incident_html_failed", report_id=str(si.id), exc_info=True)

    # Summary
    summary = {
        "total": len(incidents),
        "reported": sum(1 for i in incidents if i.reported_to_authority_at),
        "unreported": sum(1 for i in incidents if not i.reported_to_authority_at),
        "incidents": [
            {
                "id": str(i.id),
                "incident_id": str(i.incident_id),
                "deadline_at": i.deadline_at.isoformat(),
                "reported": i.reported_to_authority_at is not None,
                "reported_at": i.reported_to_authority_at.isoformat()
                if i.reported_to_authority_at
                else None,
            }
            for i in incidents
        ],
    }
    zf.writestr("incidents/summary.json", json.dumps(summary, indent=2, default=str))


async def _add_policies(
    zf: zipfile.ZipFile, db: AsyncSession, org_id: uuid.UUID
) -> None:
    result = await db.execute(
        select(Policy).where(Policy.org_id == org_id, Policy.is_active.is_(True))
    )
    policies = [
        {
            "id": str(p.id),
            "name": p.name,
            "description": p.description,
            "allowed_tools": p.allowed_tools,
            "blocked_tools": p.blocked_tools,
            "allowed_domains": p.allowed_domains,
            "blocked_domains": p.blocked_domains,
            "max_token_budget": p.max_token_budget,
            "forbidden_patterns": p.forbidden_patterns,
        }
        for p in result.scalars().all()
    ]
    zf.writestr("policies/policies.json", json.dumps(policies, indent=2, default=str))

    # Custom rules from org detector_config
    org_result = await db.execute(select(Org).where(Org.id == org_id))
    org = org_result.scalar_one_or_none()
    custom_rules = {}
    if org and org.detector_config:
        custom_rules = org.detector_config.get("custom_rules", {})
    zf.writestr(
        "policies/custom-rules.json",
        json.dumps(custom_rules, indent=2, default=str),
    )


async def _add_audit_log(
    zf: zipfile.ZipFile,
    db: AsyncSession,
    org_id: uuid.UUID,
    start: date,
    end: date,
) -> None:
    from datetime import datetime

    start_dt = datetime.combine(start, datetime.min.time(), tzinfo=UTC)
    end_dt = datetime.combine(end, datetime.max.time(), tzinfo=UTC)

    result = await db.execute(
        select(AuditLog)
        .where(
            AuditLog.org_id == org_id,
            AuditLog.created_at >= start_dt,
            AuditLog.created_at <= end_dt,
        )
        .order_by(AuditLog.created_at)
    )
    rows = [
        {
            "id": str(row.id),
            "action": row.action,
            "actor_type": row.actor_type,
            "actor_label": row.actor_label,
            "resource_type": row.resource_type,
            "resource_id": row.resource_id,
            "created_at": row.created_at.isoformat(),
            "details": row.details,
        }
        for row in result.scalars().all()
    ]
    zf.writestr("audit-log/audit-log.json", json.dumps(rows, indent=2, default=str))

    zf.writestr(
        "audit-log/chain-verification.md",
        """# Audit Log Chain Verification

The audit log entries in this bundle are ordered chronologically.
For full hash-chain verification, use the standalone audit export
endpoint (`GET /api/v1/audit-log/export`) which includes per-row
hash values and the chain tip.

Verification steps:
1. Export the hash-chained audit log via the API
2. Run the offline verification script (see docs/runbook.md)
3. Compare entry counts and date ranges with this bundle
""",
    )
